// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnexfhgtqlryfkyuvihq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZXhmaGd0cWxyeWZreXV2aWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzA5NzAsImV4cCI6MjA2Nzc0Njk3MH0.QzBc3y6LXIeHbeOoYska42YS26l7DEpiRAM7Hrko-7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});